<?xml version="1.0" encoding="UTF-8"?>
<robot generated="20170123 22:09:47.282" generator="Robot 3.0.1 (Python 2.7.10 on darwin)">
<suite source="/Users/jshanahan/Prog/qa-eei/RFtests/testRobot.robot" id="s1" name="testRobot">
<test id="s1-t1" name="As a Tester I need to make sure robot is working correctly">
<kw name="SmokeTest" library="smokeTest">
<doc>Verify that webdriver and robot are working correctly</doc>
<kw name="Open Browser" library="ExtendedSelenium2Library">
<doc>Opens a new browser instance to given URL.</doc>
<arguments>
<arg>${url}</arg>
<arg>${browser}</arg>
</arguments>
<msg timestamp="20170123 22:09:47.386" level="INFO">Opening browser 'googlechrome' to base url 'https://google.com'</msg>
<kw name="Capture Page Screenshot" library="ExtendedSelenium2Library">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20170123 22:10:17.535" level="FAIL">No browser is open</msg>
<msg timestamp="20170123 22:10:17.535" level="DEBUG">Traceback (most recent call last):
  File "&lt;decorator-gen-147&gt;", line 2, in capture_page_screenshot
  File "/Users/jshanahan/Library/Python/2.7/lib/python/site-packages/Selenium2Library/keywords/keywordgroup.py", line 15, in _run_on_failure_decorator
    return method(*args, **kwargs)
  File "/Users/jshanahan/Library/Python/2.7/lib/python/site-packages/Selenium2Library/keywords/_screenshot.py", line 90, in capture_page_screenshot
    if hasattr(self._current_browser(), 'get_screenshot_as_file'):
  File "/Users/jshanahan/Library/Python/2.7/lib/python/site-packages/Selenium2Library/keywords/_browsermanagement.py", line 516, in _current_browser
    raise RuntimeError('No browser is open')</msg>
<status status="FAIL" endtime="20170123 22:10:17.535" starttime="20170123 22:10:17.532"></status>
</kw>
<msg timestamp="20170123 22:10:17.535" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No browser is open</msg>
<msg timestamp="20170123 22:10:17.536" level="FAIL">WebDriverException: Message: Can not connect to the Service chromedriver
</msg>
<msg timestamp="20170123 22:10:17.536" level="DEBUG">Traceback (most recent call last):
  File "&lt;decorator-gen-200&gt;", line 2, in open_browser
  File "/Users/jshanahan/Library/Python/2.7/lib/python/site-packages/Selenium2Library/keywords/keywordgroup.py", line 15, in _run_on_failure_decorator
    return method(*args, **kwargs)
  File "/Users/jshanahan/Library/Python/2.7/lib/python/site-packages/ExtendedSelenium2Library/__init__.py", line 214, in open_browser
    open_browser(url, browser, alias, remote_url, desired_capabilities, ff_profile_dir)
  File "&lt;decorator-gen-26&gt;", line 2, in open_browser
  File "/Users/jshanahan/Library/Python/2.7/lib/python/site-packages/Selenium2Library/keywords/keywordgroup.py", line 15, in _run_on_failure_decorator
    return method(*args, **kwargs)
  File "/Users/jshanahan/Library/Python/2.7/lib/python/site-packages/Selenium2Library/keywords/_browsermanagement.py", line 116, in open_browser
    browser = self._make_browser(browser_name,desired_capabilities,ff_profile_dir,remote_url)
  File "/Users/jshanahan/Library/Python/2.7/lib/python/site-packages/Selenium2Library/keywords/_browsermanagement.py", line 530, in _make_browser
    browser = creation_func(remote, desired_capabilities, profile_dir)
  File "/Users/jshanahan/Library/Python/2.7/lib/python/site-packages/Selenium2Library/keywords/_browsermanagement.py", line 555, in _make_chrome
    webdriver.DesiredCapabilities.CHROME, remote, desired_capabilities)
  File "/Users/jshanahan/Library/Python/2.7/lib/python/site-packages/Selenium2Library/keywords/_browsermanagement.py", line 596, in _generic_make_browser
    browser = webdriver_type()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/common/service.py", line 102, in start
    raise WebDriverException("Can not connect to the Service %s" % self.path)</msg>
<status status="FAIL" endtime="20170123 22:10:17.536" starttime="20170123 22:09:47.385"></status>
</kw>
<status status="FAIL" endtime="20170123 22:10:17.546" starttime="20170123 22:09:47.385"></status>
</kw>
<doc>Create new test run</doc>
<tags>
<tag>NewSmokeTest</tag>
</tags>
<status status="FAIL" endtime="20170123 22:10:17.547" critical="yes" starttime="20170123 22:09:47.384">WebDriverException: Message: Can not connect to the Service chromedriver
</status>
</test>
<doc>test to make sure robot framework is behaving.</doc>
<status status="FAIL" endtime="20170123 22:10:17.549" starttime="20170123 22:09:47.285"></status>
</suite>
<statistics>
<total>
<stat fail="1" pass="0">Critical Tests</stat>
<stat fail="1" pass="0">All Tests</stat>
</total>
<tag>
<stat fail="1" pass="0">NewSmokeTest</stat>
</tag>
<suite>
<stat fail="1" id="s1" name="testRobot" pass="0">testRobot</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20170123 22:10:17.535" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No browser is open</msg>
</errors>
</robot>
